spring:
  application:
    name: desimandi
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yourDatabaseName
      username: yourUsername
      password: yourPassword
      authentication-database: admin

